import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"], fallback: ['ui-sans-serif', 'sans-serif'] });

export const metadata: Metadata = {
    title: "Recovery Plus | Login",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <section
                    className={`flex justify-between bg-[--bg-login] dark:bg-[--bg-dark-sidebar] w-screen h-screen`}
                >
                    <slot />
                    {children}
                </section>
            </body>
        </html>
    );
}
